packages:
  - '.'
allowBuilds:
  esbuild: false
  workerd: true
minimumReleaseAgeExclude:
  - astro@7.3.1
  - reicon-svelte@1.0.104
  - reicon@1.2.4
  - '@astrojs/cloudflare@14.3.0'
  - miniflare@5.20260903.0-alpha
  - wrangler@4.129.0
