import * as stylex from '@stylexjs/stylex';
import { colors, fonts, space } from './tokens.stylex';

const fadeUp = stylex.keyframes({
	from: {
		opacity: 0,
		transform: 'translateY(12px)',
	},
	to: {
		opacity: 1,
		transform: 'translateY(0)',
	},
});

export const layout = stylex.create({
	shell: {
		minHeight: '100dvh',
		display: 'flex',
		flexDirection: 'column',
		backgroundColor: colors.bg,
		color: colors.fg,
	},
	main: {
		flex: '1',
		width: '100%',
	},
	container: {
		width: '100%',
		maxWidth: '72rem',
		marginInline: 'auto',
		paddingInline: space.page,
	},
	section: {
		paddingBlock: `clamp(3.5rem, 10vw, ${space['4xl']})`,
	},
	sectionHead: {
		position: 'relative',
		display: 'block',
		width: 'fit-content',
		maxWidth: '100%',
		margin: `0 0 ${space.lg}`,
	},
	sectionMark: {
		position: 'absolute',
		left: '-0.2em',
		top: '42%',
		zIndex: 0,
		color: colors.accentText,
		opacity: 0.13,
		lineHeight: 0,
		pointerEvents: 'none',
		userSelect: 'none',
		transform: 'translateY(-50%) rotate(-16deg) scale(3.4)',
		transformOrigin: 'center center',
	},
	sectionMarkTilt: {
		left: '-0.05em',
		top: '48%',
		opacity: 0.11,
		transform: 'translateY(-50%) rotate(12deg) scale(3.6)',
	},
	sectionMarkSkew: {
		left: '-0.35em',
		top: '55%',
		opacity: 0.12,
		transform: 'translateY(-50%) rotate(-8deg) scale(3.2)',
	},
	sectionMarkAskew: {
		left: '0.05em',
		top: '40%',
		opacity: 0.14,
		transform: 'translateY(-50%) rotate(18deg) scale(3.5)',
	},
	sectionTitle: {
		position: 'relative',
		zIndex: 1,
		fontFamily: fonts.display,
		fontSize: 'clamp(1.75rem, 3.5vw, 2.5rem)',
		fontWeight: 400,
		lineHeight: 1.15,
		letterSpacing: '-0.02em',
		textWrap: 'balance',
		margin: 0,
		color: colors.fg,
	},
	lede: {
		fontFamily: fonts.body,
		fontSize: '1.0625rem',
		lineHeight: 1.6,
		color: colors.muted,
		maxWidth: '36rem',
		textWrap: 'pretty',
		margin: 0,
	},
});

export const hero = stylex.create({
	root: {
		position: 'relative',
		isolation: 'isolate',
		minHeight: '100dvh',
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'flex-end',
		paddingTop: '4rem',
		paddingBottom: `clamp(3rem, 8vw, ${space['4xl']})`,
		overflow: 'hidden',
	},
	atmosphere: {
		position: 'absolute',
		inset: 0,
		zIndex: -1,
		backgroundImage: `
			radial-gradient(ellipse 80% 55% at 85% 10%, ${colors.meshA}, transparent 55%),
			radial-gradient(ellipse 60% 50% at 10% 80%, ${colors.meshB}, transparent 50%),
			radial-gradient(ellipse 50% 40% at 50% 40%, ${colors.meshC}, transparent 60%),
			linear-gradient(180deg, ${colors.bg} 0%, ${colors.bg} 100%)
		`,
		backgroundColor: colors.bg,
	},
	grain: {
		position: 'absolute',
		inset: 0,
		zIndex: -1,
		opacity: 0.32,
		pointerEvents: 'none',
		backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.55'/%3E%3C/svg%3E")`,
		mixBlendMode: 'soft-light',
	},
	inner: {
		width: '100%',
		maxWidth: '72rem',
		marginInline: 'auto',
		paddingInline: space.page,
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'flex-start',
		gap: space['2xl'],
	},
	portraitWrap: {
		display: 'block',
		width: 'min(148px, 38vw)',
		height: 'min(148px, 38vw)',
		aspectRatio: '1 / 1',
		flexShrink: 0,
		padding: '3px',
		borderRadius: '9999px',
		overflow: 'hidden',
		boxSizing: 'border-box',
		backgroundImage: `conic-gradient(
			from 210deg,
			${colors.portraitRim},
			${colors.portraitRing},
			${colors.borderSubtle},
			${colors.portraitRim}
		)`,
		boxShadow: `
			0 0 0 1px ${colors.portraitRing},
			0 0 40px ${colors.portraitGlow},
			0 12px 28px color-mix(in oklab, ${colors.shadow} 12%, transparent)
		`,
		animationName: fadeUp,
		animationDuration: '700ms',
		animationTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
		animationFillMode: 'both',
	},
	portrait: {
		display: 'block',
		width: '100%',
		height: '100%',
		maxWidth: 'none',
		aspectRatio: '1 / 1',
		borderRadius: '9999px',
		objectFit: 'cover',
		objectPosition: 'center top',
		boxShadow: `inset 0 0 0 1px ${colors.imageOutline}`,
	},
	copy: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'flex-start',
		gap: space.xl,
		maxWidth: '40rem',
	},
	brand: {
		fontFamily: fonts.display,
		fontSize: 'clamp(3.25rem, 10vw, 6.5rem)',
		fontWeight: 400,
		lineHeight: 0.95,
		letterSpacing: '-0.03em',
		textWrap: 'balance',
		margin: 0,
		color: colors.fg,
		animationName: fadeUp,
		animationDuration: '700ms',
		animationDelay: '80ms',
		animationTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
		animationFillMode: 'both',
	},
	headline: {
		fontFamily: fonts.body,
		fontSize: 'clamp(1.125rem, 2.2vw, 1.375rem)',
		fontWeight: 500,
		lineHeight: 1.35,
		letterSpacing: '-0.015em',
		textWrap: 'balance',
		margin: 0,
		color: colors.fg,
		animationName: fadeUp,
		animationDuration: '700ms',
		animationDelay: '140ms',
		animationTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
		animationFillMode: 'both',
	},
	support: {
		fontFamily: fonts.body,
		fontSize: '1rem',
		lineHeight: 1.6,
		color: colors.muted,
		maxWidth: '34rem',
		textWrap: 'pretty',
		margin: 0,
		animationName: fadeUp,
		animationDuration: '700ms',
		animationDelay: '200ms',
		animationTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
		animationFillMode: 'both',
	},
	ctas: {
		display: 'flex',
		flexWrap: 'wrap',
		alignItems: 'center',
		gap: space.md,
		marginTop: space.xs,
		animationName: fadeUp,
		animationDuration: '700ms',
		animationDelay: '280ms',
		animationTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
		animationFillMode: 'both',
	},
});

export const button = stylex.create({
	base: {
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		gap: space.sm,
		height: '2.875rem',
		paddingInline: '1.25rem',
		borderRadius: '10px',
		fontFamily: fonts.body,
		fontSize: '0.9375rem',
		fontWeight: 600,
		letterSpacing: '-0.01em',
		borderWidth: 0,
		borderStyle: 'none',
		cursor: 'pointer',
		textDecoration: 'none',
		transitionProperty: 'background-color, color, transform',
		transitionDuration: '160ms',
		transitionTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
		':active': {
			transform: 'scale(0.96)',
		},
	},
	primary: {
		backgroundColor: colors.primary,
		color: colors.primaryFg,
		':hover': {
			backgroundColor: colors.primaryHover,
			color: colors.primaryFg,
		},
		':focus-visible': {
			outlineColor: colors.ring,
			color: colors.primaryFg,
		},
	},
	ghost: {
		backgroundColor: colors.secondary,
		color: colors.fg,
		':hover': {
			backgroundColor: colors.accent,
			color: colors.accentFg,
		},
	},
});

export const about = stylex.create({
	grid: {
		display: 'grid',
		gap: space['2xl'],
		'@media (min-width: 768px)': {
			gridTemplateColumns: 'minmax(0, 0.9fr) minmax(0, 1.1fr)',
			alignItems: 'start',
		},
	},
	meta: {
		display: 'flex',
		flexDirection: 'column',
		gap: space.md,
		fontFamily: fonts.body,
		fontSize: '0.9375rem',
		color: colors.muted,
	},
	metaRow: {
		display: 'flex',
		gap: space.sm,
		alignItems: 'center',
	},
	metaLabel: {
		fontSize: '0.75rem',
		fontWeight: 500,
		letterSpacing: '0.06em',
		textTransform: 'uppercase',
		color: colors.muted,
		minWidth: '5.5rem',
	},
	body: {
		fontFamily: fonts.body,
		fontSize: '1.0625rem',
		lineHeight: 1.65,
		color: colors.fg,
		maxWidth: '38rem',
		textWrap: 'pretty',
		margin: 0,
	},
	experience: {
		marginTop: space['2xl'],
		paddingTop: space.xl,
		boxShadow: `inset 0 1px 0 ${colors.borderSubtle}`,
	},
	expRole: {
		fontFamily: fonts.body,
		fontSize: '1rem',
		fontWeight: 600,
		letterSpacing: '-0.01em',
		margin: 0,
		color: colors.fg,
	},
	expMeta: {
		fontFamily: fonts.body,
		fontSize: '0.875rem',
		color: colors.muted,
		margin: `${space.xs} 0 ${space.md}`,
	},
	expList: {
		margin: 0,
		paddingInlineStart: '1.1rem',
		display: 'flex',
		flexDirection: 'column',
		gap: space.sm,
	},
	expItem: {
		fontFamily: fonts.body,
		fontSize: '0.9375rem',
		lineHeight: 1.55,
		color: colors.fg,
		textWrap: 'pretty',
	},
});

export const skills = stylex.create({
	groups: {
		display: 'flex',
		flexDirection: 'column',
		gap: space.xl,
		marginTop: space.xl,
	},
	group: {
		display: 'flex',
		flexDirection: 'column',
		gap: space.sm,
	},
	label: {
		fontFamily: fonts.body,
		fontSize: '0.6875rem',
		fontWeight: 500,
		letterSpacing: '0.06em',
		textTransform: 'uppercase',
		color: colors.muted,
		margin: 0,
	},
	list: {
		display: 'flex',
		flexWrap: 'wrap',
		gap: '0.35rem',
		padding: 0,
		listStyle: 'none',
		margin: 0,
	},
	chip: {
		display: 'inline-flex',
		alignItems: 'center',
		gap: '0.35rem',
		fontFamily: fonts.body,
		fontSize: '0.75rem',
		fontWeight: 500,
		letterSpacing: '-0.01em',
		lineHeight: 1.2,
		color: colors.fg,
		backgroundColor: colors.secondary,
		paddingBlock: '0.3rem',
		paddingInline: '0.55rem',
		borderRadius: '6px',
		transitionProperty: 'background-color, color',
		transitionDuration: '140ms',
		transitionTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
		':hover': {
			backgroundColor: colors.accent,
			color: colors.accentFg,
		},
	},
	mark: {
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		width: '0.875rem',
		height: '0.875rem',
		flexShrink: 0,
		color: 'inherit',
		opacity: 0.85,
	},
});

export const projects = stylex.create({
	list: {
		display: 'flex',
		flexDirection: 'column',
		margin: `${space['2xl']} 0 0`,
		padding: 0,
		listStyle: 'none',
		gap: 0,
	},
	item: {
		paddingBlock: space.xl,
		boxShadow: `inset 0 -1px 0 ${colors.borderSubtle}`,
		':last-child': {
			boxShadow: 'none',
		},
	},
	body: {
		display: 'grid',
		gap: space.md,
		'@media (min-width: 720px)': {
			gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1.15fr)',
			gap: space['2xl'],
			alignItems: 'start',
		},
	},
	heading: {
		display: 'flex',
		flexDirection: 'column',
		gap: space.sm,
	},
	name: {
		fontFamily: fonts.body,
		fontSize: 'clamp(1.0625rem, 2vw, 1.1875rem)',
		fontWeight: 600,
		letterSpacing: '-0.015em',
		lineHeight: 1.3,
		margin: 0,
		color: colors.fg,
		textWrap: 'balance',
	},
	stack: {
		fontFamily: fonts.body,
		fontSize: '0.8125rem',
		fontWeight: 500,
		lineHeight: 1.45,
		color: colors.accentText,
		margin: 0,
		textWrap: 'pretty',
	},
	bullets: {
		margin: 0,
		paddingInlineStart: '1.1rem',
		display: 'flex',
		flexDirection: 'column',
		gap: '0.45rem',
	},
	bullet: {
		fontFamily: fonts.body,
		fontSize: '0.9375rem',
		lineHeight: 1.5,
		color: colors.muted,
		textWrap: 'pretty',
	},
});

export const contact = stylex.create({
	panel: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'flex-start',
		gap: space.xl,
		marginTop: space['2xl'],
		paddingTop: space['2xl'],
		boxShadow: `inset 0 1px 0 ${colors.borderSubtle}`,
	},
	actions: {
		display: 'flex',
		flexWrap: 'wrap',
		alignItems: 'center',
		gap: space.md,
	},
});

export const footer = stylex.create({
	root: {
		paddingBlock: `clamp(2rem, 5vw, ${space['3xl']})`,
		marginTop: 'auto',
	},
	inner: {
		display: 'flex',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		alignItems: 'baseline',
		gap: space.md,
		maxWidth: '72rem',
		marginInline: 'auto',
		paddingInline: space.page,
		fontFamily: fonts.body,
		fontSize: '0.8125rem',
		color: colors.muted,
		boxShadow: `inset 0 1px 0 ${colors.borderSubtle}`,
		paddingTop: space.xl,
	},
	mark: {
		fontFamily: fonts.display,
		fontStyle: 'italic',
		fontSize: '1rem',
		letterSpacing: '-0.02em',
		color: colors.fg,
	},
});
